# Generated by Django 5.2.1 on 2025-05-14 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0003_complain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Complains',
        ),
    ]
