# Generated by Django 5.2.1 on 2025-06-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        ('people_management', '0007_repair_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Name and contact number of a person to contact during leave.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='work_handover',
            field=models.TextField(blank=True, help_text='Details about work delegation or handover arrangements.', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the leave request was submitted.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(help_text='The employee submitting this leave request.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='people_management.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(help_text='The last day of the requested leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(help_text='The type of leave being requested.', on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='Detailed reason for the leave request (min. 20, max. 500 characters).'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the leave request was reviewed.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The user (manager/admin) who reviewed this leave request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(help_text='The first day of the requested leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the leave request.', max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=0, help_text='Maximum days allowed for this leave type per year.'),
        ),
    ]
