# Generated by Django 5.2.1 on 2025-06-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 6, 9)),
            preserve_default=False,
        ),
    ]
